# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import kube_bullet_grpc_pb2 as kube__bullet__grpc__pb2


class KubeBulletInterfaceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckServerConnection = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/CheckServerConnection',
                request_serializer=kube__bullet__grpc__pb2.Ping.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.Pong.FromString,
                )
        self.SetupRobot = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/SetupRobot',
                request_serializer=kube__bullet__grpc__pb2.RobotSetupRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.RobotStatus.FromString,
                )
        self.SendRobotJointPositionCommand = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/SendRobotJointPositionCommand',
                request_serializer=kube__bullet__grpc__pb2.RobotJointPositionCommand.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.RobotStatus.FromString,
                )
        self.MoveArmThroughEefPoses = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/MoveArmThroughEefPoses',
                request_serializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.RobotStatus.FromString,
                )
        self.MoveArmThroughEefPosesWithFeedback = channel.unary_stream(
                '/kube_bullet_grpc.KubeBulletInterface/MoveArmThroughEefPosesWithFeedback',
                request_serializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesResponse.FromString,
                )
        self.ExecuteGripperControlPrimitive = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/ExecuteGripperControlPrimitive',
                request_serializer=kube__bullet__grpc__pb2.GripperControlPrimitive.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.GripperStatus.FromString,
                )
        self.ReuqestGripperStatus = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/ReuqestGripperStatus',
                request_serializer=kube__bullet__grpc__pb2.GripperStatusRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.GripperStatus.FromString,
                )
        self.SetupCamera = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/SetupCamera',
                request_serializer=kube__bullet__grpc__pb2.CameraSetupRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.CameraStatus.FromString,
                )
        self.RequestRendering = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/RequestRendering',
                request_serializer=kube__bullet__grpc__pb2.RenderingRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.CameraStatus.FromString,
                )
        self.SetupObject = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/SetupObject',
                request_serializer=kube__bullet__grpc__pb2.ObjectSetupRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.ObjectState.FromString,
                )
        self.RequestObjectState = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/RequestObjectState',
                request_serializer=kube__bullet__grpc__pb2.ObjectStateRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.ObjectState.FromString,
                )
        self.RequestObjectGraspPose = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/RequestObjectGraspPose',
                request_serializer=kube__bullet__grpc__pb2.ObjectGraspPoseRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.ObjectGraspPose.FromString,
                )
        self.CreatePoseMarkers = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/CreatePoseMarkers',
                request_serializer=kube__bullet__grpc__pb2.PoseMarkerCreateRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.PoseMarkerCreateResponse.FromString,
                )
        self.SetupSimulator = channel.unary_unary(
                '/kube_bullet_grpc.KubeBulletInterface/SetupSimulator',
                request_serializer=kube__bullet__grpc__pb2.SimulatorSetupRequest.SerializeToString,
                response_deserializer=kube__bullet__grpc__pb2.SimulatorStatus.FromString,
                )


class KubeBulletInterfaceServicer(object):
    """Interface exported by the server.
    """

    def CheckServerConnection(self, request, context):
        """Healthy check | Handshake
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupRobot(self, request, context):
        """robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendRobotJointPositionCommand(self, request, context):
        """robot position control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveArmThroughEefPoses(self, request, context):
        """control primitives
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveArmThroughEefPosesWithFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteGripperControlPrimitive(self, request, context):
        """gripper
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReuqestGripperStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupCamera(self, request, context):
        """camera
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestRendering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupObject(self, request, context):
        """object
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestObjectState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestObjectGraspPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePoseMarkers(self, request, context):
        """debugging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetupSimulator(self, request, context):
        """simulation setup
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KubeBulletInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckServerConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckServerConnection,
                    request_deserializer=kube__bullet__grpc__pb2.Ping.FromString,
                    response_serializer=kube__bullet__grpc__pb2.Pong.SerializeToString,
            ),
            'SetupRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupRobot,
                    request_deserializer=kube__bullet__grpc__pb2.RobotSetupRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.RobotStatus.SerializeToString,
            ),
            'SendRobotJointPositionCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendRobotJointPositionCommand,
                    request_deserializer=kube__bullet__grpc__pb2.RobotJointPositionCommand.FromString,
                    response_serializer=kube__bullet__grpc__pb2.RobotStatus.SerializeToString,
            ),
            'MoveArmThroughEefPoses': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveArmThroughEefPoses,
                    request_deserializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.RobotStatus.SerializeToString,
            ),
            'MoveArmThroughEefPosesWithFeedback': grpc.unary_stream_rpc_method_handler(
                    servicer.MoveArmThroughEefPosesWithFeedback,
                    request_deserializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.MoveArmThroughEefPosesResponse.SerializeToString,
            ),
            'ExecuteGripperControlPrimitive': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteGripperControlPrimitive,
                    request_deserializer=kube__bullet__grpc__pb2.GripperControlPrimitive.FromString,
                    response_serializer=kube__bullet__grpc__pb2.GripperStatus.SerializeToString,
            ),
            'ReuqestGripperStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReuqestGripperStatus,
                    request_deserializer=kube__bullet__grpc__pb2.GripperStatusRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.GripperStatus.SerializeToString,
            ),
            'SetupCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupCamera,
                    request_deserializer=kube__bullet__grpc__pb2.CameraSetupRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.CameraStatus.SerializeToString,
            ),
            'RequestRendering': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRendering,
                    request_deserializer=kube__bullet__grpc__pb2.RenderingRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.CameraStatus.SerializeToString,
            ),
            'SetupObject': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupObject,
                    request_deserializer=kube__bullet__grpc__pb2.ObjectSetupRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.ObjectState.SerializeToString,
            ),
            'RequestObjectState': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestObjectState,
                    request_deserializer=kube__bullet__grpc__pb2.ObjectStateRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.ObjectState.SerializeToString,
            ),
            'RequestObjectGraspPose': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestObjectGraspPose,
                    request_deserializer=kube__bullet__grpc__pb2.ObjectGraspPoseRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.ObjectGraspPose.SerializeToString,
            ),
            'CreatePoseMarkers': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePoseMarkers,
                    request_deserializer=kube__bullet__grpc__pb2.PoseMarkerCreateRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.PoseMarkerCreateResponse.SerializeToString,
            ),
            'SetupSimulator': grpc.unary_unary_rpc_method_handler(
                    servicer.SetupSimulator,
                    request_deserializer=kube__bullet__grpc__pb2.SimulatorSetupRequest.FromString,
                    response_serializer=kube__bullet__grpc__pb2.SimulatorStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kube_bullet_grpc.KubeBulletInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KubeBulletInterface(object):
    """Interface exported by the server.
    """

    @staticmethod
    def CheckServerConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/CheckServerConnection',
            kube__bullet__grpc__pb2.Ping.SerializeToString,
            kube__bullet__grpc__pb2.Pong.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetupRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/SetupRobot',
            kube__bullet__grpc__pb2.RobotSetupRequest.SerializeToString,
            kube__bullet__grpc__pb2.RobotStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendRobotJointPositionCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/SendRobotJointPositionCommand',
            kube__bullet__grpc__pb2.RobotJointPositionCommand.SerializeToString,
            kube__bullet__grpc__pb2.RobotStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveArmThroughEefPoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/MoveArmThroughEefPoses',
            kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.SerializeToString,
            kube__bullet__grpc__pb2.RobotStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveArmThroughEefPosesWithFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/kube_bullet_grpc.KubeBulletInterface/MoveArmThroughEefPosesWithFeedback',
            kube__bullet__grpc__pb2.MoveArmThroughEefPosesRequest.SerializeToString,
            kube__bullet__grpc__pb2.MoveArmThroughEefPosesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteGripperControlPrimitive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/ExecuteGripperControlPrimitive',
            kube__bullet__grpc__pb2.GripperControlPrimitive.SerializeToString,
            kube__bullet__grpc__pb2.GripperStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReuqestGripperStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/ReuqestGripperStatus',
            kube__bullet__grpc__pb2.GripperStatusRequest.SerializeToString,
            kube__bullet__grpc__pb2.GripperStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetupCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/SetupCamera',
            kube__bullet__grpc__pb2.CameraSetupRequest.SerializeToString,
            kube__bullet__grpc__pb2.CameraStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestRendering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/RequestRendering',
            kube__bullet__grpc__pb2.RenderingRequest.SerializeToString,
            kube__bullet__grpc__pb2.CameraStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetupObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/SetupObject',
            kube__bullet__grpc__pb2.ObjectSetupRequest.SerializeToString,
            kube__bullet__grpc__pb2.ObjectState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestObjectState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/RequestObjectState',
            kube__bullet__grpc__pb2.ObjectStateRequest.SerializeToString,
            kube__bullet__grpc__pb2.ObjectState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestObjectGraspPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/RequestObjectGraspPose',
            kube__bullet__grpc__pb2.ObjectGraspPoseRequest.SerializeToString,
            kube__bullet__grpc__pb2.ObjectGraspPose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePoseMarkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/CreatePoseMarkers',
            kube__bullet__grpc__pb2.PoseMarkerCreateRequest.SerializeToString,
            kube__bullet__grpc__pb2.PoseMarkerCreateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetupSimulator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kube_bullet_grpc.KubeBulletInterface/SetupSimulator',
            kube__bullet__grpc__pb2.SimulatorSetupRequest.SerializeToString,
            kube__bullet__grpc__pb2.SimulatorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
