robot_name: "ur10e_cell"
urdf_path: "/workspace/kube_bullet/robots/robot_assets/ur10e_cell/ur10e_cell.urdf"

active_components:
  - ur10e
  - robotiq_gripper

ur10e:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  initial_positions: [0, -1.57079632, 1.57079632, -1.57079632, -1.57079632, 0]
  default_controller: position_controller
  goal_tolerance: 0.002
  # ik
  ik_base_link: base_link_inertia
  # ik_eef_link: wrist_3_link
  ik_eef_link: tool0

robotiq_gripper:
  joints:
    - finger_joint # 26
  initial_positions: [0.2]
  default_controller: position_controller
  
  mimic_parent: finger_joint
  mimic_joints:
    left_inner_finger_joint: # 28
      gain: -1
    right_outer_knuckle_joint: # 30
      gain: 1
    right_inner_finger_joint: # 32
      gain: -1
