robot_name: "ur10e_cell"
urdf_path: "/workspace/kube_bullet/robots/robot_assets/ur10e_cell/ur10e_cell.urdf"

controllable_components:
  - arm_ur10e
  - robotiq_gripper

arm_ur10e:
  joint_indices: [3, 4, 5, 6, 7, 8]
  initial_positions: [0, -0.5, 0.5, -0.5, -0.5, 0]

robotiq_gripper:
  joint_indices: [26] # finger_joint
  initial_positions: [0.3]
  mimics:
    right_outer_knucle_joint:
      idx: 30
      gain: 1
    left_inner_finger_joint:
      idx: 28
      gain: -1
    right_inner_finger_joint:
      idx: 32
      gain: -1
